### ISSUE TITLE
Float number visual bug with add server requirement

### ISSUE THREAD

**Issue by xXBuilderBXx** [discordplace/discord.place#59]
If one of the requirements is not met it will show a long float number that should be rounded without a decimal place 00%

![image](https://github.com/user-attachments/assets/8833e469-9d0b-42f1-82c1-92708b2f2c20)

**Comment by chimpdev** [comment]
Fixed [#94afaad](https://github.com/discordplace/discord.place/commit/94afaaddabf2699af789ae3a753e1f9b56464220)
