### ISSUE TITLE
Suggestion some footer links should open in a new tab instead of the current tab

### ISSUE THREAD

**Issue by xXBuilderBXx** [discordplace/discord.place#61]
These external links in the footer could be improved by opening in a new tab instead of the user leaving the website.
Use html attribute :)
`<a target="_blank">`

![image](https://github.com/user-attachments/assets/ebb7cbdc-db21-4777-8d44-51c414614e6c)

**Comment by chimpdev** [comment]
Fixed https://github.com/discordplace/discord.place/commit/dd6eb5b024fa03984d72fa4d01649bfdd8659c12
