### ISSUE TITLE
Öneriler ve Sorunlar

### ISSUE THREAD

**Issue by ErveI** [discordplace/discord.place#65]
## **Yazım Hataları**
• Botların sayfasındaki yorum kısmında "Sahibi olduğunuz sunuculara yorum yapamazsınız." Yazısı var. "Size ait olan botlara yorum yapamazsınız." cümlesi daha doğru olur.
![image](https://github.com/user-attachments/assets/83b8b931-d760-4aee-b1cb-a7da8942b90a)

• Botun geliştiricisini "Sahibi" olarak belirtmek bana göre kötü bir tanım. Sanki botu canlı olarak belirtmişsiz gibi geliyor o yüzden "Geliştiricisi" tanımı daha doğru olur.
![image](https://github.com/user-attachments/assets/7d45313d-f3ea-428e-8349-f89bfe84971e)

## **Sorunlar**
• Mobil tarayıcı üzerinden yorum yapılamıyor. İncelemeye gönder butonu tıklanamaz olarak kalmış. Bu sorun bazen meydana geliyor ve ilk tıklamada mesaj iletilmiyor.

## **Öneriler**
• https://api.discord.place/bots/:id endpoint kısmına daha fazla veri eklenebilir örneğin. Oy verenleri array olarak verebilir profilleri img/gif verir kaç kere oy verdi vs. "En çok oy verenler" kısmındaki verileri gönderir yani. Pek gerekli bi veri değil fakat işe yarabilir bence.
![image](https://github.com/user-attachments/assets/6089ff56-92a7-430d-87c8-8120c4e6f409)

• Botun açıklamasının altında olan tag'ları ayarlanabilir kılmak işe yarabilir örneğin 5 tane ekliyor ama ilk eklenmiş olanı gösteriyor. Geliştirici onu göstermek istemeyebilir o yüzden ayarlanabilir olması kullanıcı açısından avantaj sağlar.
![image](https://github.com/user-attachments/assets/9544c699-09b7-474e-ab1a-ee916ebaf128)

• https://api.discord.place/bots/:botid/voters/:userid endpointe oy verebilme engelinin ne zaman kalkacağını  milisaniye cinsinden gösteren bilgi eklenebilir.

**Comment by kardespro** [comment]
@chimpdev

**Comment by chimpdev** [comment]
> Botların sayfasındaki yorum kısmında "Sahibi olduğunuz sunuculara yorum yapamazsınız." Yazısı var. "Size ait olan botlara yorum yapamazsınız." cümlesi daha doğru olur. 

Düzeltildi https://github.com/discordplace/discord.place/commit/30d299aa5ab1e7ad457fca7ccd686e380cc10131

> Botun geliştiricisini "Sahibi" olarak belirtmek bana göre kötü bir tanım. Sanki botu canlı olarak belirtmişsiz gibi geliyor o yüzden "Geliştiricisi" tanımı daha doğru olur.

Sahibi daha iyi bir tanım. Geliştirici başka bir şeydir, sahibi olmak başka bir şeydir. Siz botun sadece sahibi olarak hiç geliştiricilik yapmamışta olabilirsiniz örneğin. Bu yüzden bu tanım bu şekilde kalacak.

> Mobil tarayıcı üzerinden yorum yapılamıyor. İncelemeye gönder butonu tıklanamaz olarak kalmış. Bu sorun bazen meydana geliyor ve ilk tıklamada mesaj iletilmiyor.

Mobil ve bilgisayarda girdiğiniz site aynı. Böyle bir hatanın sadece mobilde olmasının pek mümkünatı yok gibi görünüyor ancak tahminlerimize göre "Yıldız" seçmeyi unuttuğunuzdan dolayı buton aktif olmuyor. Artık "Yıldız" seçmeniz gerektiğini hatırlatması için bir uyarı gözükecek.

> https://api.discord.place/bots/:id endpoint kısmına daha fazla veri eklenebilir örneğin. Oy verenleri array olarak verebilir profilleri img/gif verir kaç kere oy verdi vs. "En çok oy verenler" kısmındaki verileri gönderir yani. Pek gerekli bi veri değil fakat işe yarabilir bence.

https://api.discord.place/bots/:id/voters?page=1&limit=12 kullanarak zaten bu verilere erişebilirsiniz lakin bu sizin kullanmanız için değil, sitenin kullanması için bir endpoint. Bu yüzden her an değişebilir ve size haber verilmeyebilir. Kullanmanızı tavsiye etmiyorum. Botların kullanması için özel bir endpoint ekleyecek miyiz, hayır.

> Botun açıklamasının altında olan tag'ları ayarlanabilir kılmak işe yarabilir örneğin 5 tane ekliyor ama ilk eklenmiş olanı gösteriyor. Geliştirici onu göstermek istemeyebilir o yüzden ayarlanabilir olması kullanıcı açısından avantaj sağlar.

Eğer botu yönetme sayfasında seçtiğiniz tüm kategorileri kaldırıp, sırayla seçerseniz ilk seçtiğiniz hangi kategori ise botunuzun kartında da o gözükür. Bilerek yapılmış bir şey değil ancak bunu yaparak botunuzun kartında hangi kategorinin yazacağını seçebilirsiniz.

> https://api.discord.place/bots/:botid/voters/:userid endpointe oy verebilme engelinin ne zaman kalkacağını milisaniye cinsinden gösteren bilgi eklenebilir.

Oylar istisna olmadan verildikten tam 24 saat sonra kalkar. Bu endpoint zaten size dönüt olarak kullanıcının son 24 saatte oy verip vermediğini gösteriyor. Eğer oy vermediyse, zaten oy verebilme engelinin olmadığına işaret eder. Eğer son 24 saatte kullanıcı oy verdiyse, dönütün içerisinde ki `lastVote`'yi kullanarak son oy verdiği tarihin üzerinden ne kadar geçtiğini hesaplayabilirsiniz. Yani tekrar oy verebilmesi için ne kadar zaman kaldığını hesaplayabilirsiniz. Bu yüzden bunu milisaniye cinsinden buraya ekleme gereği duymuyoruz.

**Comment by chimpdev** [comment]
> Bunu düşünerek bu hatayı yazmıştım yıldızları fulleyip tekrar denemiştim genede olmamıştı o yüzden bu hatayı bildirdim birkaç kere tıklamama rağmen göndermemişti.

Minimum 64 karakter yazmanız gerekiyorken 63 karakter vs. yazmış olabilirsiniz o halde. Böyle bir şeyle biz karşılaşmadık şahsen.

> Ben bunu ayar olarak önermiştim nasıl yapılacağını sormamıştım. Eğer değiştirmek isteseydim tabi bi yolunu bulmaya çalışırdım. Kullanıcılara böyle bir seçenek sunmak kullanıcı deneyimi artırır diye düşünmüştüm ve bunu öneri olarak sana sunmak istemiştim. Genede önerimi dikkate aldığın için teşekkürler 👍

Bizde kullanıcılara ayar olarak eklemenin gereksiz olduğunu düşünüyoruz şu an.

> Değil Developer'ın türkçesi Geliştirici olarak geçiyor Discord üzerinde Botlar (Application) olarak geçiyor ve Application Policy'leri Developer adı altında paylaşıyor. Referans: [Developer Terms of Service](https://support-dev.discord.com/hc/articles/8562894815383-Discord-Developer-Terms-of-Service) [Developer Policy](https://support-dev.discord.com/hc/articles/8563934450327-Discord-Developer-Policy). Ayrıca Sahibi kelimesinin ingilizcesi Owner olarak geçiyor. Owner kelimesi genellikle Discord'da sunucu sahibi için kullanılıyor.

Doğru fakat benim anlatmaya çalıştığım bu değildi.

> Ayrıca sanki bu açıklamada bana gönderme yaptınız gibime geliyor. Axios'u catch yapmakla uğraşmak istememek kodlamayla uğraşmadığım anlamına gelmiyor. Tembellik ettim o an sen bana değiştireceğimizi söylediğin an ben oy kontrollerini catch haline getirmiştim bile. Ayrıca sana nasıl yapılacağını sormamıştım. Error olarak neden bu veriyi paylaştığınızı anlayamamıştım. Çünkü bir sürü Bot listte bulundum [Top.gg](https://top.gg/tr) [Discord Bot List](https://discordbotlist.com/) [Discordsunucu](https://discordsunucu.com/) [Discord Bots](https://discord.bots.gg/) [Discords](https://discords.com/) (Ayrıca bir süreliğine oy kontrollerimi bu site üzerinde yapmıştım (Site sahibiyle anlaşma yapmıştım)) Bu kadar sitede Electra'yı barındırmıştım ve hiç biri oy verilmeme verisini error olarak return etmemişti. Bunu açıklama gereği duymak bile beni üzdü reiz.

Yanlış anlamışsınız çünkü sizinle ilgili bir şey dememiştim. Yani sizin geliştiriciliğiniz ile ilgili herhangi bir şey demedim. Anlatmaya çalıştığım şey şu:

- Ortada bir ekip var ve siz yöneticisiniz, geliştirici değil.
- Ekip geliştiricilerle dolu ve botu sizin isteklerinize göre geliştiriyorlar.
- Daha çok tanınmak ve botu büyütmek için botunuzu websitemize ekliyorsunuz.

Bu durumda siz geliştiriciden ziyade botun sahibi durumunda oluyorsunuz. Eğer ekipte çalışan geliştiriciyseniz bile aynı zamanda botun sahibi siz oluyorsunuz. Owner kelimesi Discord'da sunucu sahibi için kullanılıyor olsa bile bot sahipleri içinde kullanılıyor. (örneğin bot takımı sahipleri vs.)
